name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # rama que activar√° el deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: first-vision-480408-d1
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/first-vision-480408-d1/studios-laris .

      - name: Push Docker image
        run: |
          docker push gcr.io/first-vision-480408-d1/studios-laris

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy studios-laris \
            --image gcr.io/first-vision-480408-d1/studios-laris \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
