name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: first-vision-480408-d1
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Create Service Account JSON file
        run: |
          printf "%s" "${{ secrets.GCP_SA_KEY }}" > $GITHUB_WORKSPACE/gcloud-key.json

      - name: Submit to Cloud Build & Deploy to Cloud Run
        run: |
          export CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE=$GITHUB_WORKSPACE/gcloud-key.json
          
          gcloud builds submit . \
            --tag gcr.io/first-vision-480408-d1/studios-laris
          
          gcloud run deploy studios-laris \
            --image gcr.io/first-vision-480408-d1/studios-laris \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
